CREATE TABLE Centro (
   id_centro      INTEGER     PRIMARY KEY /* GENERATED BY DEFAULT AS IDENTITY */,
   nombre         INTEGER     NOT NULL,
   titularidad    CHAR(7)     CHECK (titularidad IN ('pública', 'privada')),
   direccion      JSON
);

CREATE TABLE Estudiante (
   id_estudiante  INTEGER       PRIMARY KEY /* GENERATED BY DEFAULT AS IDENTITY */,
   nombre         VARCHAR(250)  NOT NULL,
   nacimiento     DATE          NOT NULL,
   centro         INTEGER,

   constraint fk_est_cen FOREIGN KEY(centro) REFERENCES Centro(id_centro)
      ON DELETE SET NULL
      on UPDATE CASCADE
);

INSERT INTO Centro VALUES 
   (11004866, 'IES Castillo de Luna', 'pública', '{"tipo_via": "calle", "via": "Navalcán", "numero": null, "cp": 11520, "municipio": "Rota", "provincia": "Cádiz", "telefono": 956243552, "email": "11004866.edu@juntadeandalucia.es", "web": "https://www.iescastillodeluna.es"}'),
   (11700603, 'IES Pintor Juan Lara', 'pública', '{"tipo_via": "calle", "via": "Camino del Águila", "numero": 6, "cp": 11500, "municipio": "El Puerto de Santa María", "provincia": "Cádiz", "telefono": 956243502, "email": "11700603.edu@juntadeandalucia.es", "web": "https://www.iesjuanlara.es"}'),
   (11007533, 'IES Arroyo Hondo', 'pública', '{"tipo_via": "calle", "via": "Maestro Manuel Casal", "numero": 2, "cp": 11520, "municipio": "Rota", "provincia": "Cádiz", "telefono": 956243253, "fax": 956243257,"email": "11007533.edu@juntadeandalucia.es", "web": "https://www.iesarroyohondo.es"}');
